version: '3'
services:
  odoo:
    container_name: e0.bigodoo.net
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "9001:8069"
      - "9002:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

  db:
    container_name: postgresdb
    image: postgres:12.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo_db
      - POSTGRES_PASSWORD=odoo_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5501:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data:
  odoo-data:
